### ISSUE TITLE
mod crashes server?

### ISSUE THREAD

**Issue by marcoroegner** [John-Development/mobproof_end_crystals_mod#10]
I tested the mod with my other mods in single player, worked fine.
Pushed the mod to my server-> crash on load.

And here are the serverlogs:

2023-05-04T20:43:14.233295950Z [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 100 4096 May  4 22:42 /data'
2023-05-04T20:43:14.237952071Z [init] Resolved version given 1.19.4 into 1.19.4 and major version 1.19
2023-05-04T20:43:15.093997471Z [init] Resolving type given FABRIC
2023-05-04T20:43:19.656526980Z [init] Setting initial memory to 1G and max to 10G
2023-05-04T20:43:19.660892257Z [init] Starting the Minecraft server...
2023-05-04T20:43:20.245231466Z Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
2023-05-04T20:43:21.621995147Z 2023/05/04 22:43:21 Stopping with rcon-cli
2023-05-04T20:43:21.654905769Z 2023-05-04T22:43:21.654+0200	ERROR	mc-server-runner	Failed to stop using rcon-cli	{"error": "exit status 1"}
2023-05-04T20:43:21.654937908Z 2023-05-04T22:43:21.654+0200	INFO	mc-server-runner	Sending 'stop' to Minecraft server...
2023-05-04T20:43:21.654940301Z 2023-05-04T22:43:21.654+0200	INFO	mc-server-runner	Waiting for completion...
2023-05-04T20:43:22.023895466Z [22:43:22] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
2023-05-04T20:43:22.220572358Z [22:43:22] [ForkJoinPool-1-worker-3/WARN]: Mod com_github_shevek_parallelgzip uses the version af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
2023-05-04T20:43:22.305757677Z [22:43:22] [ForkJoinPool-1-worker-1/WARN]: Mod chunkloaders uses the version 1.2.3a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '3a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
2023-05-04T20:43:22.517376463Z [22:43:22] [main/INFO]: Loading 147 mods:
2023-05-04T20:43:22.517409578Z 	- adapaxels 1.4.2+1.19.4
2023-05-04T20:43:22.517411986Z 	- appleskin 2.4.3+mc1.19.4
2023-05-04T20:43:22.517413066Z 	- architectury 8.1.80
2023-05-04T20:43:22.517414068Z 	- armorposer 1.4.0
2023-05-04T20:43:22.517415377Z 	- backpacked 2.2.0
2023-05-04T20:43:22.517416372Z 	- balm-fabric 6.0.2
2023-05-04T20:43:22.517417362Z 	- better-fabric-console 1.1.4
2023-05-04T20:43:22.517418487Z 	   |-- adventure-platform-fabric 5.8.0
2023-05-04T20:43:22.517425542Z 	   |    |-- net_kyori_adventure-api 4.13.0
2023-05-04T20:43:22.517426827Z 	   |    |-- net_kyori_adventure-key 4.13.0
2023-05-04T20:43:22.517427854Z 	   |    |-- net_kyori_adventure-platform-api 4.2.0
2023-05-04T20:43:22.517428884Z 	   |    |-- net_kyori_adventure-text-logger-slf4j 4.13.0
2023-05-04T20:43:22.517429995Z 	   |    |-- net_kyori_adventure-text-minimessage 4.13.0
2023-05-04T20:43:22.517431040Z 	   |    |-- net_kyori_adventure-text-serializer-gson 4.13.0
2023-05-04T20:43:22.517432158Z 	   |    |-- net_kyori_adventure-text-serializer-plain 4.13.0
2023-05-04T20:43:22.517433218Z 	   |    |-- net_kyori_examination-api 1.3.0
2023-05-04T20:43:22.517434245Z 	   |    \-- net_kyori_examination-string 1.3.0
2023-05-04T20:43:22.517435321Z 	   |-- com_typesafe_config 1.4.2
2023-05-04T20:43:22.517436345Z 	   |-- io_leangen_geantyref_geantyref 1.3.13
2023-05-04T20:43:22.517437383Z 	   |-- net_fabricmc_mapping-io 0.3.0
2023-05-04T20:43:22.517438446Z 	   |-- net_kyori_adventure-text-serializer-legacy 4.13.0
2023-05-04T20:43:22.517439526Z 	   |-- org_fusesource_jansi_jansi 2.4.0
2023-05-04T20:43:22.517440555Z 	   |-- org_jline_jline 3.21.0
2023-05-04T20:43:22.517441598Z 	   |-- org_jline_jline-terminal-jansi 3.21.0
2023-05-04T20:43:22.517442633Z 	   |-- org_spongepowered_configurate-core 4.1.2
2023-05-04T20:43:22.517443656Z 	   \-- org_spongepowered_configurate-hocon 4.1.2
2023-05-04T20:43:22.517444722Z 	- bettersleeping 0.6.1+1.19
2023-05-04T20:43:22.517445725Z 	   |-- bettersleeping-core 0.6.1
2023-05-04T20:43:22.517446801Z 	   \-- org_apache_commons_commons-text 1.9
2023-05-04T20:43:22.517447860Z 	- betterthanmending 1.3.0
2023-05-04T20:43:22.517448873Z 	- bitsandchisels 2.7.1
2023-05-04T20:43:22.517449912Z 	   \-- stacc 1.5.2+boneless
2023-05-04T20:43:22.517450942Z 	- blossom 1.0.7
2023-05-04T20:43:22.517451943Z 	- bluemap 3.13
2023-05-04T20:43:22.517452973Z 	- bowinfinityfix 2.5.0
2023-05-04T20:43:22.517453984Z 	- bypass_anvil_restriction 1.0.4+1.19.4
2023-05-04T20:43:22.517455072Z 	   |-- ch_skyfy_tomlconfiglib_toml-config-lib 1.0.2
2023-05-04T20:43:22.517456126Z 	   |-- io_github_microutils_kotlin-logging-jvm 3.0.4
2023-05-04T20:43:22.517457169Z 	   \-- net_peanuuutz_tomlkt-jvm 0.1.7
2023-05-04T20:43:22.517458747Z 	- carpet 1.4.101+v230319
2023-05-04T20:43:22.517459727Z 	- carpet-extra 1.4.100
2023-05-04T20:43:22.517460699Z 	- chunkloaders 1.2.3a
2023-05-04T20:43:22.517461667Z 	- cloth-config 10.0.96
2023-05-04T20:43:22.517463943Z 	   \-- cloth-basic-math 0.6.1
2023-05-04T20:43:22.517465177Z 	- comforts 6.2.0+1.19.4
2023-05-04T20:43:22.517466204Z 	   |-- cardinal-components-base 5.1.0
2023-05-04T20:43:22.517467242Z 	   |-- cardinal-components-entity 5.1.0
2023-05-04T20:43:22.517468281Z 	   \-- spectrelib 0.12.4+1.19.2
2023-05-04T20:43:22.517469307Z 	- connectivity 1.19.4-4.2
2023-05-04T20:43:22.517470289Z 	- craftingcraft 15.0.1
2023-05-04T20:43:22.517471302Z 	- debugify 1.19.4+2.2
2023-05-04T20:43:22.517472289Z 	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
2023-05-04T20:43:22.517473390Z 	- enchantedshulkers 1.1.2
2023-05-04T20:43:22.517474415Z 	   |-- com_moandjiezana_toml_toml4j 0.7.2
2023-05-04T20:43:22.517475446Z 	   \-- mm 2.3
2023-05-04T20:43:22.517477472Z 	- ender_dragon_egg_respawn 1.0.0
2023-05-04T20:43:22.517478527Z 	- fabric-api 0.80.0+1.19.4
2023-05-04T20:43:22.517479565Z 	   |-- fabric-api-base 0.4.25+504944c8f4
2023-05-04T20:43:22.517480603Z 	   |-- fabric-api-lookup-api-v1 1.6.26+504944c8f4
2023-05-04T20:43:22.517481643Z 	   |-- fabric-biome-api-v1 13.0.8+348a9c64f4
2023-05-04T20:43:22.517482712Z 	   |-- fabric-block-api-v1 1.0.7+e022e5d1f4
2023-05-04T20:43:22.517483740Z 	   |-- fabric-blockrenderlayer-v1 1.1.35+c2e6f674f4
2023-05-04T20:43:22.517484769Z 	   |-- fabric-client-tags-api-v1 1.0.16+504944c8f4
2023-05-04T20:43:22.517485823Z 	   |-- fabric-command-api-v1 1.2.28+f71b366ff4
2023-05-04T20:43:22.517486831Z 	   |-- fabric-command-api-v2 2.2.7+504944c8f4
2023-05-04T20:43:22.517487849Z 	   |-- fabric-commands-v0 0.2.45+df3654b3f4
2023-05-04T20:43:22.517488871Z 	   |-- fabric-containers-v0 0.1.55+df3654b3f4
2023-05-04T20:43:22.517489884Z 	   |-- fabric-content-registries-v0 3.5.10+ae0966baf4
2023-05-04T20:43:22.517490972Z 	   |-- fabric-convention-tags-v1 1.4.2+9a7c5daaf4
2023-05-04T20:43:22.517492000Z 	   |-- fabric-crash-report-info-v1 0.2.16+aeb40ebef4
2023-05-04T20:43:22.517493072Z 	   |-- fabric-data-generation-api-v1 11.4.1+504944c8f4
2023-05-04T20:43:22.517494198Z 	   |-- fabric-dimensions-v1 2.1.46+7f87f8faf4
2023-05-04T20:43:22.517495239Z 	   |-- fabric-entity-events-v1 1.5.14+504944c8f4
2023-05-04T20:43:22.517496274Z 	   |-- fabric-events-interaction-v0 0.5.0+76ba65ebf4
2023-05-04T20:43:22.517497294Z 	   |-- fabric-events-lifecycle-v0 0.2.53+df3654b3f4
2023-05-04T20:43:22.517498376Z 	   |-- fabric-game-rule-api-v1 1.0.34+a1ccd7bff4
2023-05-04T20:43:22.517499448Z 	   |-- fabric-item-api-v1 2.1.18+504944c8f4
2023-05-04T20:43:22.517500476Z 	   |-- fabric-item-group-api-v1 3.0.6+043f9acff4
2023-05-04T20:43:22.517502736Z 	   |-- fabric-key-binding-api-v1 1.0.34+504944c8f4
2023-05-04T20:43:22.517503991Z 	   |-- fabric-keybindings-v0 0.2.32+df3654b3f4
2023-05-04T20:43:22.517505017Z 	   |-- fabric-lifecycle-events-v1 2.2.16+504944c8f4
2023-05-04T20:43:22.517506044Z 	   |-- fabric-loot-api-v2 1.1.28+75e98211f4
2023-05-04T20:43:22.517507145Z 	   |-- fabric-loot-tables-v1 1.1.32+9e7660c6f4
2023-05-04T20:43:22.517508167Z 	   |-- fabric-message-api-v1 5.1.2+504944c8f4
2023-05-04T20:43:22.517509319Z 	   |-- fabric-mining-level-api-v1 2.1.40+49abcf7ef4
2023-05-04T20:43:22.517510348Z 	   |-- fabric-models-v0 0.3.31+504944c8f4
2023-05-04T20:43:22.517511367Z 	   |-- fabric-networking-api-v1 1.3.2+504944c8f4
2023-05-04T20:43:22.517512452Z 	   |-- fabric-networking-v0 0.3.42+df3654b3f4
2023-05-04T20:43:22.517513535Z 	   |-- fabric-object-builder-api-v1 7.0.4+504944c8f4
2023-05-04T20:43:22.517514562Z 	   |-- fabric-particles-v1 1.0.24+f1e4495bf4
2023-05-04T20:43:22.517515578Z 	   |-- fabric-recipe-api-v1 1.0.9+a1ccd7bff4
2023-05-04T20:43:22.517516650Z 	   |-- fabric-registry-sync-v0 2.2.1+504944c8f4
2023-05-04T20:43:22.517517743Z 	   |-- fabric-renderer-api-v1 2.2.6+504944c8f4
2023-05-04T20:43:22.517518765Z 	   |-- fabric-renderer-indigo 1.1.2+81e8c576f4
2023-05-04T20:43:22.517519795Z 	   |-- fabric-renderer-registries-v1 3.2.39+df3654b3f4
2023-05-04T20:43:22.517520851Z 	   |-- fabric-rendering-data-attachment-v1 0.3.29+afca2f3ef4
2023-05-04T20:43:22.517521884Z 	   |-- fabric-rendering-fluids-v1 3.0.22+504944c8f4
2023-05-04T20:43:22.517523188Z 	   |-- fabric-rendering-v0 1.1.42+df3654b3f4
2023-05-04T20:43:22.517524265Z 	   |-- fabric-rendering-v1 2.1.2+504944c8f4
2023-05-04T20:43:22.517525292Z 	   |-- fabric-resource-conditions-api-v1 2.3.2+e6c7d4eef4
2023-05-04T20:43:22.517526403Z 	   |-- fabric-resource-loader-v0 0.11.3+1e1fb126f4
2023-05-04T20:43:22.517527448Z 	   |-- fabric-screen-api-v1 1.0.46+504944c8f4
2023-05-04T20:43:22.517528955Z 	   |-- fabric-screen-handler-api-v1 1.3.21+504944c8f4
2023-05-04T20:43:22.517530047Z 	   |-- fabric-sound-api-v1 1.0.10+504944c8f4
2023-05-04T20:43:22.517531097Z 	   |-- fabric-transfer-api-v1 3.1.2+504944c8f4
2023-05-04T20:43:22.517532112Z 	   \-- fabric-transitive-access-wideners-v1 3.0.4+504944c8f4
2023-05-04T20:43:22.517533165Z 	- fabric-language-kotlin 1.9.4+kotlin.1.8.21
2023-05-04T20:43:22.517534197Z 	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
2023-05-04T20:43:22.517535275Z 	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
2023-05-04T20:43:22.517536309Z 	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
2023-05-04T20:43:22.517537341Z 	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
2023-05-04T20:43:22.517539994Z 	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
2023-05-04T20:43:22.517541180Z 	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
2023-05-04T20:43:22.517542274Z 	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
2023-05-04T20:43:22.517543313Z 	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
2023-05-04T20:43:22.517544378Z 	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
2023-05-04T20:43:22.517545526Z 	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
2023-05-04T20:43:22.517546601Z 	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
2023-05-04T20:43:22.517547697Z 	- fabric-permissions-api-v0 0.2-SNAPSHOT
2023-05-04T20:43:22.517548727Z 	- fabricloader 0.14.19
2023-05-04T20:43:22.517549712Z 	- ferritecore 5.2.0
2023-05-04T20:43:22.517550696Z 	- framework 0.6.4
2023-05-04T20:43:22.517551680Z 	   |-- com_electronwill_night-config_core 3.6.6
2023-05-04T20:43:22.517552717Z 	   |-- com_electronwill_night-config_toml 3.6.6
2023-05-04T20:43:22.517553792Z 	   |-- org_javassist_javassist 3.29.2-GA
2023-05-04T20:43:22.517554833Z 	   \-- org_reflections_reflections 0.10.2
2023-05-04T20:43:22.517555869Z 	- fwaystones 3.1.0+mc1.19.4
2023-05-04T20:43:22.517556878Z 	- jamlib 0.6.0+1.19.4
2023-05-04T20:43:22.517557863Z 	- java 17
2023-05-04T20:43:22.517558827Z 	- kleeslabs 14.1.0
2023-05-04T20:43:22.517559815Z 	- krypton 0.2.2
2023-05-04T20:43:22.517560875Z 	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
2023-05-04T20:43:22.517562099Z 	- lithium 0.11.1
2023-05-04T20:43:22.517563103Z 	- memoryleakfix 1.0.0
2023-05-04T20:43:22.517564114Z 	- minecraft 1.19.4
2023-05-04T20:43:22.517565121Z 	- minecraft-command-permissions 1.6.1
2023-05-04T20:43:22.517566120Z 	- mixintrace 1.1.1+1.17
2023-05-04T20:43:22.517567123Z 	- mob_proof_crystals 2.3.1-1.19.4
2023-05-04T20:43:22.517568120Z 	- nochatreports 1.19.4-v2.1.1
2023-05-04T20:43:22.517569147Z 	   |-- fabric-rendering-v1 2.0.2+ae0966bad8
2023-05-04T20:43:22.517570231Z 	   \-- fabric-screen-api-v1 1.0.44+8c25edb4d8
2023-05-04T20:43:22.517571279Z 	- owo 0.10.3+1.19.4
2023-05-04T20:43:22.517572274Z 	   \-- blue_endless_jankson 1.2.2
2023-05-04T20:43:22.517573321Z 	- physicsmod 2.12.4
2023-05-04T20:43:22.517574303Z 	- rightclickharvest 3.1.0+1.19.4
2023-05-04T20:43:22.517575311Z 	- roughlyenoughitems 11.0.597
2023-05-04T20:43:22.517576307Z 	   \-- error_notifier 1.0.9
2023-05-04T20:43:22.517578830Z 	- roughlyenoughresources 2.8.0
2023-05-04T20:43:22.517580088Z 	- showmeyourskin 1.6.3+1.19.4
2023-05-04T20:43:22.517581101Z 	   |-- cardinal-components-base 5.1.0
2023-05-04T20:43:22.517582221Z 	   |-- cardinal-components-entity 5.1.0
2023-05-04T20:43:22.517583269Z 	   \-- cicada 0.4.0
2023-05-04T20:43:22.517584270Z 	- silkspawners 1.1.2
2023-05-04T20:43:22.517585257Z 	- sit 1.19.4-23
2023-05-04T20:43:22.517586248Z 	- smoothchunk 1.19.4-3.0
2023-05-04T20:43:22.517587240Z 	- starlight 1.1.1+fabric.ae22326
2023-05-04T20:43:22.517588310Z 	- supermartijn642configlib 1.1.6
2023-05-04T20:43:22.517589325Z 	- supermartijn642corelib 1.1.7
2023-05-04T20:43:22.517590309Z 	- textile_backup 2.5.0-1.19
2023-05-04T20:43:22.517591351Z 	   |-- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
2023-05-04T20:43:22.517592440Z 	   |-- org_apache_commons_commons-compress 1.21
2023-05-04T20:43:22.517593460Z 	   \-- org_tukaani_xz 1.9
2023-05-04T20:43:22.517594493Z 	- yet_another_config_lib 2.5.0+1.19.4
2023-05-04T20:43:22.932124069Z [22:43:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
2023-05-04T20:43:22.979404387Z [22:43:22] [main/INFO]: Compatibility level set to JAVA_17
2023-05-04T20:43:23.680771875Z [22:43:23] [main/INFO]: Preloading Debugify
2023-05-04T20:43:23.943622733Z [22:43:23] [main/INFO]: Loaded configuration file for Lithium: 114 options available, 2 override(s) found
2023-05-04T20:43:24.886442096Z [22:43:24] [main/WARN]: Force disabled MC-135971 because it's conflicting with: carpet
2023-05-04T20:43:25.027456556Z [22:43:25] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
2023-05-04T20:43:25.053810132Z [22:43:25] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
2023-05-04T20:43:25.165792378Z [22:43:25] [main/WARN]: Error loading class: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage (java.lang.ClassNotFoundException: fr/catcore/server/translations/api/resource/language/SystemDelegatedLanguage)
2023-05-04T20:43:25.191282462Z [22:43:25] [main/INFO]: [MemoryLeakFix] Will be applying 1 memory leak fixes!
2023-05-04T20:43:25.191472776Z [22:43:25] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [biomeTemperatureLeak]
2023-05-04T20:43:26.064409008Z [22:43:26] [main/INFO]: Initializing Better Fabric Console...
2023-05-04T20:43:26.064588188Z [22:43:26] [main/INFO]: Initializing Better Fabric Console mappings...
2023-05-04T20:43:26.921210314Z [22:43:26] [main/INFO]: Reading mappings...
2023-05-04T20:43:28.719338376Z [22:43:28] [main/INFO]: Done in 1.7980 seconds.
2023-05-04T20:43:29.110311727Z May 04, 2023 10:43:29 PM org.jline.utils.Log logr
2023-05-04T20:43:29.110358285Z WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2023-05-04T20:43:31.476969652Z [39m[22:43:31 INFO] [main]: [FabricLoader/Mixin][m Mixing common.MixinFriendlyByteBuf from mixins/common/nochatreports.mixins.json into net.minecraft.class_2540[m
2023-05-04T20:43:31.477456828Z [39m[22:43:31 INFO] [main]: [FabricLoader/Mixin][m Renaming synthetic method lambda$onWriteJsonWithCodec$1(Ljava/lang/Object;Ljava/lang/String;)Lio/netty/handler/codec/EncoderException; to mdd22dc2$nochatreports$lambda$onWriteJsonWithCodec$1$0 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports[m
2023-05-04T20:43:31.477692636Z [39m[22:43:31 INFO] [main]: [FabricLoader/Mixin][m Renaming synthetic method lambda$onReadJsonWithCodec$0(Ljava/lang/String;)Lio/netty/handler/codec/DecoderException; to mdd22dc2$nochatreports$lambda$onReadJsonWithCodec$0$1 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports[m
2023-05-04T20:43:40.561124419Z [33m[22:43:40 WARN] [main]: [FabricLoader/Mixin][m Method overwrite conflict for getClimateSettings in architectury.mixins.json:BiomeAccessor from mod architectury, previously written by carpet.mixins.Biome_scarpetMixin. Skipping method.[m
2023-05-04T20:43:41.257101496Z [39m[22:43:41 INFO] [main]: [FabricLoader/Mixin][m Mixing server.MixinDedicatedServer from mixins/common/nochatreports.mixins.json into net.minecraft.class_3176[m
2023-05-04T20:43:42.980230088Z [39m[22:43:42 INFO] [main]: [Reflections][m Reflections took 182 ms to scan 1 urls, producing 2 keys and 25 values[m
2023-05-04T20:43:43.234895528Z [39m[22:43:43 INFO] [main]: [FabricLoader/Mixin][m Mixing server.MixinServerGamePacketListenerImpl from mixins/common/nochatreports.mixins.json into net.minecraft.class_3244[m
2023-05-04T20:43:43.255100132Z [33m[22:43:43 WARN] [main]: [FabricLoader/Mixin][m Method overwrite conflict for getConnection in fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric-networking-api-v1, previously written by carpet.mixins.ServerGamePacketListenerImpl_coreMixin. Skipping method.[m
2023-05-04T20:43:43.256101601Z [33m[22:43:43 WARN] [main]: [FabricLoader/Mixin][m Method overwrite conflict for getConnection in krypton.mixins.json:shared.network.util.ServerPlayNetworkHandlerAccessor from mod krypton, previously written by carpet.mixins.ServerGamePacketListenerImpl_coreMixin. Skipping method.[m
2023-05-04T20:43:43.348574003Z [31m[22:43:43 ERROR] [main]: [Main][m Failed to start the minecraft server[m
2023-05-04T20:43:43.348598559Z net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'mob_proof_crystals'
2023-05-04T20:43:43.348600476Z 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348601848Z 	at com.supermartijn642.core.registry.RegistryEntryAcceptor$Handler.gatherAnnotatedFields(RegistryEntryAcceptor.java:72) ~[supermartijn642corelib-1.1.7-fabric-mc1.19.jar:?]
2023-05-04T20:43:43.348607772Z 	at com.supermartijn642.core.CoreLib.beforeInitialize(CoreLib.java:64) ~[supermartijn642corelib-1.1.7-fabric-mc1.19.jar:?]
2023-05-04T20:43:43.348609263Z 	at net.minecraft.server.Main.handler$cig000$supermartijn642corelib$beforeInitServer(Main.java:1526) ~[server-intermediary.jar:?]
2023-05-04T20:43:43.348610523Z 	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
2023-05-04T20:43:43.348611647Z 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348612814Z 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348614034Z 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348615176Z 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348616346Z 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.4-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
2023-05-04T20:43:43.348617537Z Caused by: java.lang.RuntimeException: Cannot load class net.mobProofCrystals.mobProofCrystals in environment type SERVER
2023-05-04T20:43:43.348618724Z 	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348619970Z 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348621231Z 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348623535Z 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348624805Z 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348625971Z 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348627138Z 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
2023-05-04T20:43:43.348628228Z 	at java.lang.Class.forName0(Native Method) ~[?:?]
2023-05-04T20:43:43.348629305Z 	at java.lang.Class.forName(Unknown Source) ~[?:?]
2023-05-04T20:43:43.348630458Z 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348631676Z 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348632875Z 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.19.jar:?]
2023-05-04T20:43:43.348634122Z 	... 9 more
2023-05-04T20:43:43.767939051Z 2023-05-04T22:43:43.767+0200	INFO	mc-server-runner	Done

**Comment by John-Development** [comment]
Found the issue, fixed in [release 2.3.2](https://github.com/John-Development/mobproof-end-crystals-mod/releases/tag/2.3.2)
