### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Hexze** [John-Development/mobproof_end_crystals_mod#11]
The mod page states that this is compatible with 1.20.x, but it fails to launch on a fabric 1.20.1 server.

[00:57:33] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Mob proof crystals' (mob_proof_crystals) 2.3.2-1.20 with any version that is compatible with:
                 - minecraft 1.20.1
Unmet dependency listing:
         - Mod 'Mob proof crystals' (mob_proof_crystals) 2.3.2-1.20 requires any 1.19.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.22.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.22.jar:?]

**Comment by John-Development** [comment]
Sorry for the inconvenience. I updated the file and now It should be accepting the correct version.
Thank you for the feedback!
