### ISSUE TITLE
Newest version crashes on start

### ISSUE THREAD

**Issue by Mewtwoy** [John-Development/mobproof_end_crystals_mod#2]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mob_proof_crystals'!
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$zze000$stopFabricInit(MinecraftClient:3360)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/DumperOptions
    at net.mobProofCrystals.mobProofCrystals.onInitialize(mobProofCrystals.java:26)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement$$Lambda$2406/914505647.accept(Unknown Source)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement$$Lambda$2407/1720782061.accept(Unknown Source)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.DumperOptions
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 15 more

**Comment by John-Development** [comment]
Im checking this.

**Comment by John-Development** [comment]
This issue should be fixed in version 1.0.2
